# Generated by Django 2.0.2 on 2018-03-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('people_number', models.IntegerField()),
                ('tour_time', models.IntegerField()),
                ('tour_date', models.DateField()),
                ('Special_Accomidations', models.TextField()),
            ],
        ),
    ]
