# Generated by Django 2.0.2 on 2018-03-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addReserv', '0003_auto_20180315_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='tour_time',
            field=models.IntegerField(choices=[(10, '10:00am-11:00pm'), (11, '11:00am-12:00pm'), (12, '12:00pm-1:00pm'), (1, '1:00pm-2:00pm')], max_length=2),
        ),
    ]
