# Generated by Django 2.0.2 on 2018-03-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addReserv', '0004_auto_20180315_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='tour_time',
            field=models.IntegerField(choices=[(9, '9:00am-10:00pm'), (10, '10:00am-11:00pm'), (11, '11:00am-12:00pm'), (12, '12:00pm-1:00pm'), (1, '1:00pm-2:00pm'), (2, '2:00pm-3:00pm'), (3, '3:00pm-4:00pm')], max_length=2),
        ),
    ]
