# Generated by Django 2.0.2 on 2018-03-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addReserv', '0005_auto_20180315_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Special_Accomidations',
            field=models.TextField(blank=True),
        ),
    ]
